"""Initial migration

Revision ID: a14e6300cf9e
Revises: 
Create Date: 2025-10-29 13:29:17.494113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a14e6300cf9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_schemas',
    sa.Column('schema_id', sa.String(length=50), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('schema_id')
    )
    op.create_index(op.f('ix_form_schemas_schema_id'), 'form_schemas', ['schema_id'], unique=False)
    op.create_table('panchayats',
    sa.Column('panchayat_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('block', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('panchayat_id')
    )
    op.create_index(op.f('ix_panchayats_panchayat_id'), 'panchayats', ['panchayat_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('panchayat_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.panchayat_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('surveys',
    sa.Column('survey_id', sa.String(length=50), nullable=False),
    sa.Column('panchayat_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('village_name', sa.String(length=255), nullable=True),
    sa.Column('basic_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('infrastructure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sanitation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('connectivity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('land_forest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('electricity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('waste_management', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('client_timestamp', sa.DateTime(), nullable=True),
    sa.Column('server_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.panchayat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('survey_id')
    )
    op.create_index(op.f('ix_surveys_survey_id'), 'surveys', ['survey_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.survey_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_sync_logs_log_id'), 'sync_logs', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_logs_log_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_surveys_survey_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_panchayats_panchayat_id'), table_name='panchayats')
    op.drop_table('panchayats')
    op.drop_index(op.f('ix_form_schemas_schema_id'), table_name='form_schemas')
    op.drop_table('form_schemas')
    # ### end Alembic commands ###
